spring:
  application:
    name: exam2

  datasource:
    url: jdbc:postgresql://localhost:5433/parkingdb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yzwNALI2A

server:
  port: 8788
